# Generated by Django 5.2.14 on 2026-05-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asynctaskresult',
            options={'ordering': ['-id'], 'verbose_name': 'Результат асинхронного завдання', 'verbose_name_plural': 'Результати асинхронних завдань'},
        ),
    ]
