# Generated by Django 5.2.14 on 2026-05-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandoms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fandom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fandoms/'),
        ),
    ]
