# Generated by Django 5.2.14 on 2026-05-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fandoms', '0003_fandomrequest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fandom',
            options={'verbose_name': 'Фандом', 'verbose_name_plural': 'Фандоми'},
        ),
        migrations.AlterModelOptions(
            name='fandommembership',
            options={'verbose_name': 'Учасник фандому', 'verbose_name_plural': 'Учасники фандомів'},
        ),
        migrations.AlterModelOptions(
            name='fandomrequest',
            options={'verbose_name': 'Запит на створення фандому', 'verbose_name_plural': 'Запити на створення фандомів'},
        ),
        migrations.AlterField(
            model_name='fandom',
            name='category',
            field=models.CharField(choices=[('anime', 'Аніме'), ('books', 'Книги'), ('series', 'Серіали'), ('games', 'Ігри'), ('other', 'Інше')], max_length=20),
        ),
        migrations.AlterField(
            model_name='fandomrequest',
            name='category',
            field=models.CharField(choices=[('anime', 'Аніме'), ('books', 'Книги'), ('series', 'Серіали'), ('games', 'Ігри'), ('other', 'Інше')], max_length=20),
        ),
    ]
