# Generated by Django 5.2.14 on 2026-05-25 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chats', '0002_message_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name': 'Чат-кімната', 'verbose_name_plural': 'Чат-кімнати'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': 'Повідомлення', 'verbose_name_plural': 'Повідомлення'},
        ),
    ]
